public static class GameEvent
{
    public const string LECTURE_PART_FINISHED = "LECTURE_PART_FINISHED";
    public const string STUDENT_ASK_QUESTION = "STUDENT_ASK_QUESTION";
    public const string LECTION_IS_FINISHED = "LECTION_IS_FINISHED";
    public const string NEED_TO_CHANGE_SLIDE = "NEED_TO_CHANGE_SLIDE";
    public const string ASKS_FINISHED = "ASKS_FINISHED";
    public const string SLIDE_CHANGED = "SLIDE_CHANGED";
    public const string STUDENT_FINISHED_TESTING_MODULE = "STUDENT_FINISHED_TESTING_MODULE";
    public const string STUDENT_PRESSED_TESTING_BUTTON = "STUDENT_PRESSED_TESTING_BUTTON";
    public const string STUDENT_AUDIO_RECORD_FINISHED = "STUDENT_AUDIO_RECORD_FINISHED";
}